version: 2

models:
  - name: stg_telegram_messages
    columns:
      - name: message_id
        tests:
          - not_null
          - unique

  - name: dim_channels
    columns:
      - name: channel_name
        tests:
          - not_null
          - unique

  - name: dim_dates
    columns:
      - name: date
        tests:
          - not_null
          - unique

  - name: fct_messages
    columns:
      - name: message_id
        tests:
          - not_null
          - unique
      - name: channel_name
        tests:
          - not_null
  - name: fct_product_mentions
    description: "Fact table summarizing product mentions in Telegram messages."
    columns:
      - name: product_name
        description: "Name of the mentioned product."
        tests:
          - not_null
      - name: mentions
        description: "Number of times the product was mentioned."
